use_frameworks!

platform :ios, '15.0'

source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/bigbigbig/mySpecs.git'

target 'zawsdk_ios_Example' do
  pod 'zawsdk_ios', :path => '../'
#  pod 'zawsdk_vk_ios', '0.4.0'
  target 'zawsdk_ios_Tests' do
    inherit! :search_paths

    
  end
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
